// <auto-generated />
using LolApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LolApp.Migrations
{
    [DbContext(typeof(LeagueContext))]
    [Migration("20250213164749_InitAutoSettings")]
    partial class InitAutoSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("LolApp.Data.AutoSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoAcceptQueue")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoRandomChampionSkin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoRequeue")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoRerollAram")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoSelectChampion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AutoSettings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
